const quotes = [
    "Your smile makes the world blush in quiet delight.",
    "Every heartbeat writes a love song the stars can hear.",
    "Eyes hold the gentle fire of endless sunsets.",
    "A smile lingers like a favorite melody.",
    "Even in silence, the spirit speaks softly.",
    "Warmth carried lights the corners of the soul.",
    "Every word whispered blooms into a garden of joy.",
    "Ordinary moments taste like poetry.",
    "Laughter dances softly, leaving echoes in the heart.",
    "The touch of a gentle hand makes the world feel infinite.",
    "A soft dawn can soften the night within.",
    "Every glance carries a secret promise of wonder.",
    "In warmth, even the coldest storms find peace.",
    "A voice can be a tide that calms a restless sea.",
    "Thoughts linger like perfume on the wind.",
    "The soul shines brighter than the quietest stars.",
    "Every step writes a rhythm the heart keeps.",
    "Love can be the whisper the universe holds.",
    "Even fleeting moments feel like eternity.",
    "Presence is a soft flame that lights the darkest hours.",
    "The world tilts gently at the curve of a smile.",
    "A touch can be a poem written without words.",
    "Time slows to savor a single heartbeat.",
    "Laughter is the melody that warms the soul.",
    "Every glance holds a story waiting to be told.",
    "Sunlight dances through gentle eyes.",
    "Embrace is a harbor where the heart finds rest.",
    "Stars pause to admire a quiet beauty.",
    "Words can bloom like flowers in the heart.",
    "Love flows like a river through silent moments.",
    "Even shadows are softened by warmth.",
    "Gentle winds carry whispers of hope.",
    "The smallest moments shine like constellations.",
    "A smile can ignite quiet fireworks in the soul.",
    "Whispers can be lullabies for the restless heart.",
    "Every gaze carries infinite wonder.",
    "Soft touches leave sparks that linger.",
    "Even fleeting presence can feel eternal.",
    "Hands held can calm the stormiest seas.",
    "Every heartbeat is a brushstroke on the soul.",
    "Quiet moments hum with unseen melodies.",
    "Eyes reflect the light of hidden galaxies.",
    "Laughter trickles like sunlight through leaves.",
    "Every step beside another feels like dancing on clouds.",
    "Soft voices carry the warmth of endless afternoons.",
    "Every glance plants flowers of joy.",
    "The world softens beneath gentle grace.",
    "A smile leaves traces of quiet serenity.",
    "Touches linger like petals falling softly.",
    "Presence transforms ordinary spaces into sanctuaries.",
    "Every sigh is a gentle sonnet.",
    "Eyes hold oceans of unspoken wonder.",
    "A gentle flame lights the darkest hours.",
    "Laughter is a river that waters joy.",
    "Words shared plant gardens of happiness.",
    "Glances are lighthouses guiding the heart home.",
    "Moments feel infinite when embraced fully.",
    "Every heartbeat dances to its own melody.",
    "Presence is a song the universe hums softly.",
    "Soft whispers ripple through silent rooms.",
    "Even brief touches leave lasting warmth.",
    "Every smile carries the weight of joy.",
    "Gazes are constellations in quiet night skies.",
    "Soft hands can anchor drifting hearts.",
    "Every step writes invisible poetry on the ground.",
    "Presence lingers like sunlight through morning mist.",
    "Gentle words are petals falling on the soul.",
    "Every heartbeat is a quiet celebration.",
    "Smiles bloom like flowers in hidden gardens.",
    "Every glance is a secret the stars keep.",
    "Whispers carry the fragrance of hope.",
    "Hands intertwined write stories without words.",
    "Every moment is a verse in the poem of life.",
    "Soft touches leave trails of gentle light.",
    "Every gaze is a mirror reflecting warmth.",
    "Moments shared become timeless memories.",
    "Every smile is a spark lighting quiet skies.",
    "Presence transforms ordinary days into poetry.",
    "Every heartbeat echoes through the silent spaces.",
    "Soft laughter rises like sunlight after rain.",
    "Every whisper leaves a lasting imprint.",
    "Glances linger like melodies in the mind.",
    "Touches are the brushstrokes of invisible art.",
    "Every moment is a gentle tide in the ocean of life.",
    "Smiles carry the glow of hidden suns.",
    "Every heartbeat paints colors unseen.",
    "Whispers float like leaves on calm rivers.",
    "Presence is a gentle flame that warms unseen corners.",
    "Every glance writes a verse on the wind.",
    "Soft words bloom into gardens of quiet joy.",
    "Every smile is a sunrise on a hidden horizon.",
    "Touches are echoes of timeless poetry.",
    "Every heartbeat is a gentle rhythm in the soul.",
    "Presence is the quiet music of the universe.",
    "Every moment shared is a story written in light.",
    "Smiles illuminate paths where shadows linger.",
    "Every whisper carries the weight of wonder.",
    "Glances hold the secrets of endless skies.",
    "Touches are silent songs sung to the heart.",
    "Every heartbeat whispers of unseen worlds.",
    "Presence is a gentle wave washing over the soul.",
    "Every smile leaves a trace of endless warmth.",
    "Soft laughter is the echo of hidden suns.",
    "Every glance paints the sky with unseen colors.",
    "Touches linger like the last notes of a song."
];



const para = document.getElementById("quote");

function generateNumber(){
    return Math.floor(Math.random() * quotes.length);
}
let prevNum = generateNumber();

function generateQuote(){
    
    let quoteNumber = generateNumber();

    if (quoteNumber === prevNum) {
        quoteNumber = (quoteNumber + 1) % quotes.length;
    }
    
    para.textContent = quotes[quoteNumber];
    prevNum = quoteNumber
}