const quotes = [
"\"I am going to be the king of the pirates!\" - Monkey D. Luffy",
"\"Plus Ultra!\" - Izuku Midoriya",
"\"I am justice!\" - Light Yagami",
"\"Push through the pain. Giving up hurts more.\" - Vegeta",
"\"Hard work is worthless for those who don’t believe in themselves.\" - Naruto Uzumaki",
"\"The world is cruel, but also very beautiful.\" - Mikasa Ackerman",
"\"A lesson without pain is meaningless.\" - Edward Elric",
"\"If you can’t do something, then don’t. Just believe in someone who can.\" - Erwin Smith",
"\"I am the bone of my sword.\" - Shirou Emiya",
"\"Fear is not evil. It tells you what your weakness is.\" - Gildarts Clive",
"\"Whatever you lose, you'll find it again.\" - Monkey D. Luffy",
"\"I won’t run away anymore.\" - Shinji Ikari",
"\"If you don’t like your destiny, don’t accept it.\" - Naruto Uzumaki",
"\"I am the hope of the universe!\" - Goku",
"\"Power comes in response to a need, not a desire.\" - Goku",
"\"I’ll take a potato chip… and eat it!\" - Light Yagami",
"\"We don’t know what tomorrow holds. That’s why we can enjoy today.\" - Natsu Dragneel",
"\"A real ninja never gives up.\" - Jiraiya",
"\"If you can’t do anything, then don’t.\" - Erwin Smith",
"\"No matter how deep the night, it always turns to day.\" - Brook",
"\"I will protect everyone.\" - Tanjiro Kamado",
"\"Set your heart ablaze.\" - Kyojuro Rengoku",
"\"I am going to surpass you.\" - Sasuke Uchiha",
"\"A person grows up when he’s able to overcome hardships.\" - Jiraiya",
"\"I don’t know everything. I just know what I know.\" - Levi Ackerman",
"\"In our society, letting others find out you’re nice is a death sentence.\" - Hitagi Senjougahara",
"\"I am not weak.\" - Saitama",
"\"Whatever happens, happens.\" - Spike Spiegel",
"\"The ticket to the future is always open.\" - Vash the Stampede",
"\"Even if I die, I’ll protect you.\" - Kirito",
"\"I refuse to let my fear control me.\" - Eren Yeager",
"\"We don’t know what tomorrow holds.\" - Natsu Dragneel",
"\"I’ll become a hero.\" - Izuku Midoriya",
"\"If you can’t beat the game, you can’t clear it.\" - Kirito",
"\"I will become Hokage.\" - Naruto Uzumaki",
"\"There’s no shame in falling down.\" - Shoto Todoroki",
"\"A sword wields no strength unless the hand that holds it has courage.\" - Hero (Black Clover)",
"\"I’ll keep moving forward.\" - Eren Yeager",
"\"It’s not the face that makes someone a monster.\" - Naruto Uzumaki",
"\"Surpass your limits.\" - Yami Sukehiro",
"\"I choose to protect my friends.\" - Gon Freecss",
"\"We don’t know what tomorrow holds.\" - Erwin Smith",
"\"I won’t forgive anyone who hurts my friends.\" - Monkey D. Luffy",
"\"If you can do one thing, hone it to perfection.\" - Jiraiya",
"\"No matter what, I’ll keep smiling.\" - Nami",
"\"I’ll never give up.\" - Asta",
"\"You should enjoy the little detours.\" - Ging Freecss",
"\"Even a small step forward is progress.\" - Izuku Midoriya",
"\"Humans are interesting.\" - Satoru Gojo",
"\"Throughout heaven and earth, I alone am the honored one.\" - Satoru Gojo",
"\"I am the strongest.\" - Saitama",
"\"There’s no such thing as coincidence.\" - Master Oogway",
"\"Protecting someone means giving them a place to belong.\" - Kakashi Hatake",
"\"We don’t know what tomorrow holds.\" - Mikasa Ackerman",
"\"I am not alone.\" - Subaru Natsuki",
"\"If I can’t do something, I’ll train until I can.\" - Rock Lee",
"\"It’s okay to cry.\" - Tanjiro Kamado",
"\"You can’t sit around envying other people’s worlds.\" - Subaru Natsuki",
"\"I’ll become the Pirate King.\" - Monkey D. Luffy",
"\"I won’t let anyone die.\" - Eren Yeager",
"\"There’s nothing crueler than letting a dream end.\" - Shanks",
"\"I’ll protect this world.\" - Ichigo Kurosaki",
"\"Bankai.\" - Ichigo Kurosaki",
"\"If miracles only happen once, what are they called the second time?\" - Toshiro Hitsugaya",
"\"I am the storm.\" - Madara Uchiha",
"\"Wake up to reality.\" - Madara Uchiha",
"\"I’ll rewrite destiny.\" - Lelouch Lamperouge",
"\"The only ones who should kill are those prepared to be killed.\" - Lelouch Lamperouge",
"\"If the king doesn’t move, then his subjects won’t follow.\" - Lelouch Lamperouge",
"\"I am going to win.\" - Ash Ketchum",
"\"Believe in yourself.\" - Naruto Uzumaki",
"\"I fight for my friends.\" - Natsu Dragneel",
"\"We are the Survey Corps.\" - Erwin Smith",
"\"My soldiers, rage!\" - Erwin Smith",
"\"You are already dead.\" - Kenshiro",
"\"I am atomic.\" - Cid Kagenou",
"\"This is my ninja way.\" - Naruto Uzumaki",
"\"I will surpass All Might.\" - Izuku Midoriya",
"\"Even if I’m weak, I’ll keep fighting.\" - Hinata Hyuga",
"\"I am the Flame Hashira.\" - Kyojuro Rengoku",
"\"I’ll end this.\" - Levi Ackerman",
"\"I will not die.\" - Zoro",
"\"Scars on the back are a swordsman’s shame.\" - Roronoa Zoro",
"\"I will protect my comrades.\" - Giyu Tomioka",
"\"No matter what, keep moving forward.\" - Eren Yeager",
"\"Strength is the only thing that matters.\" - Vegeta",
"\"I am the Saiyan Prince.\" - Vegeta",
"\"Friendship is magic.\" - Lucy Heartfilia",
"\"A true ninja never gives up.\" - Naruto Uzumaki",
"\"This world shall know pain.\" - Pain",
"\"Love is the most twisted curse.\" - Gojo Satoru",
"\"I’ll eat you up!\" - Kaneki Ken",
"\"We are all slaves to something.\" - Kenny Ackerman",
"\"I am not your tool.\" - Mikasa Ackerman",
"\"A hero always arrives late.\" - All Might",
"\"I am All Might.\" - All Might",
"\"I smile to show the pressure of heroes.\" - All Might",
"\"I won’t abandon my comrades.\" - Luffy",
"\"Even if I’m wrong, I’ll fight.\" - Eren Yeager",
"\"I choose this path.\" - Sasuke Uchiha",
"\"I am vengeance.\" - Sasuke Uchiha",
"\"If I don’t fight, I can’t win.\" - Eren Yeager",
"\"We don’t know what tomorrow holds.\" - Levi Ackerman",
"\"I am the strongest sorcerer.\" - Gojo Satoru",
"\"It’s over 9000!\" - Vegeta",
"\"I will become stronger.\" - Tanjiro Kamado",
"\"I’ll break this curse.\" - Yuta Okkotsu",
"\"Don’t underestimate humans.\" - Roy Mustang",
"\"I am the Fullmetal Alchemist.\" - Edward Elric",
"\"I won’t let anyone take my freedom.\" - Eren Yeager",
"\"Even if I die, I’ll win.\" - Goku",
"\"I will protect this smile.\" - Hinata Hyuga",
"\"I am not afraid.\" - Itachi Uchiha",
"\"Those who forgive themselves are strong.\" - Itachi Uchiha",
"\"Reality is often disappointing.\" - Thanos",
"\"I am inevitable.\" - Thanos",
"\"Whatever you do, enjoy it.\" - Monkey D. Luffy",
"\"Dreams never end.\" - Marshall D. Teach",
"\"If you’re hungry, eat.\" - Monkey D. Luffy",
"\"I’ll never lose again.\" - Roronoa Zoro",
"\"My magic is never giving up.\" - Asta",
"\"Even if I’m alone, I’ll fight.\" - Ichigo Kurosaki",
"\"You can die anytime, but living takes courage.\" - Kenshin Himura",
"\"If you can’t do it alone, do it with friends.\" - Gon Freecss",
"\"The strong eat the weak.\" - Ken Kaneki",
"\"I will keep walking.\" - Tanjiro Kamado",
"\"Heroes always find a way.\" - Deku",
"\"I’ll protect everyone’s dreams.\" - Luffy",
"\"I am the future king.\" - Meliodas",
"\"I’ll carve my own path.\" - Asta",
"\"There’s no such thing as a painless lesson.\" - Edward Elric",
"\"No matter how many times I fall, I’ll stand.\" - Naruto Uzumaki",
"\"I’ll fight until my last breath.\" - Levi Ackerman",
"\"This is my resolve.\" - Tanjiro Kamado",
"\"I am unstoppable.\" - Goku"
];

const para = document.getElementById("quote");

function generateNumber(){
    return Math.floor(Math.random() * quotes.length);
}
let prevNum = generateNumber();

function generateQuote(){
    
    let quoteNumber = generateNumber();

    if (quoteNumber === prevNum) {
        quoteNumber = (quoteNumber + 1) % quotes.length;
    }
    
    para.textContent = quotes[quoteNumber];
    prevNum = quoteNumber
}