const quotes = [
    "Your presence makes the world blush in quiet delight.",
    "Every heartbeat of yours writes a love song the stars can hear.",
    "In your eyes, I see the gentle fire of endless sunsets.",
    "Your smile lingers in my mind like a favorite melody.",
    "Even in silence, your spirit speaks to mine.",
    "The warmth you carry lights the corners of my soul.",
    "Every word you whisper blooms into a garden of joy.",
    "With you, ordinary moments taste like poetry.",
    "Your laughter dances softly, leaving echoes in my heart.",
    "The touch of your essence makes the world feel infinite.",
    "You are the gentle dawn that softens the night within me.",
    "Every glance from you is a secret promise of wonder.",
    "In your warmth, even the coldest storms find peace.",
    "Your voice is a gentle tide that calms my restless sea.",
    "The thought of you lingers like perfume on the wind.",
    "Your soul shines brighter than the quietest stars.",
    "Every step you take writes a rhythm my heart keeps.",
    "You are the whisper of love that the universe holds.",
    "Even fleeting moments with you feel like eternity.",
    "Your presence is a soft flame that lights the darkest hours.",
    "The world tilts gently when you smile my way.",
    "Your touch is a poem written on my skin.",
    "With you, time slows to savor every heartbeat.",
    "Your laughter is the melody my heart hums along with.",
    "Every look from you is a story I wish would never end.",
    "You are the sunlight that kisses the morning dew.",
    "Your embrace is a harbor where my soul rests.",
    "The sparkle in your eyes holds galaxies of wonder.",
    "With every word you speak, you paint love in my world.",
    "Your love feels like rain on parched earth.",
    "Even in shadows, your light makes everything golden.",
    "You are the gentle echo of everything beautiful.",
    "Your warmth lingers, even when you’re far away.",
    "The world feels softer because you exist in it.",
    "Your smile ignites quiet fireworks in my heart.",
    "Every whisper from you is a lullaby to my soul.",
    "You are a poem that the universe recites in secret.",
    "With you, the smallest moments are miracles.",
    "Your eyes hold oceans I could swim forever in.",
    "Even the stars pause to admire your beauty.",
    "Your love is a candle that never flickers.",
    "Every heartbeat with you is a brushstroke on my soul.",
    "You are the gentle pulse in the quiet of my world.",
    "Your voice carries the warmth of endless afternoons.",
    "With you, my heart learns the rhythm of joy.",
    "Your laughter is the sunrise my soul wakes to.",
    "You are the soft murmur of hope in every day.",
    "Every word you share plants flowers in my heart.",
    "Your gaze is a lighthouse guiding me home.",
    "With you, the night is never lonely.",
    "You are a soft song the wind hums for me.",
    "Your smile is a spark that lights all my skies.",
    "Every step beside you feels like dancing on clouds.",
    "You are the quiet miracle I never knew I needed.",
    "Your love drifts in like sunlight through leaves.",
    "Even the coldest nights are warm with your memory.",
    "Your heart is a garden where my soul blooms.",
    "Every sigh of yours is a sonnet I memorize.",
    "You are the rhythm my heart has been waiting for.",
    "With you, every silence speaks volumes.",
    "Your laughter is a river that waters my joy.",
    "Every glance from you is a treasure I keep.",
    "You are the whisper that turns chaos into calm.",
    "Your embrace is the music my soul dances to.",
    "With you, even ordinary days feel sacred.",
    "Your love writes verses on the walls of my heart.",
    "You are the calm after the storm, the sun after rain.",
    "Every thought of you is a spark in my mind.",
    "Your touch is the melody my body remembers.",
    "With you, the world seems softer, kinder, brighter.",
    "Your eyes are constellations that guide me at night.",
    "Every heartbeat beside you is poetry in motion.",
    "You are the flame that keeps my spirit warm.",
    "Your smile carries the weight of endless joy.",
    "With you, every shadow is kissed with light.",
    "Your presence is a river that flows through my soul.",
    "Every word you utter is a petal falling on my heart.",
    "You are the gentle wind that lifts me higher.",
    "Your love lingers like the sweetest fragrance.",
    "With you, the world is a garden in bloom.",
    "Every moment with you is a line in our story.",
    "You are the warmth in a cold morning, the calm in a storm.",
    "Your laughter is a lighthouse in my foggiest hours.",
    "With you, every goodbye feels like a promise of return.",
    "You are the sunlight that dances on my skin.",
    "Every glance from you writes a verse on my heart.",
    "Your love is a soft tide that reshapes my soul.",
    "With you, I discover worlds I never knew existed.",
    "You are the dream that lingers after I wake.",
    "Every whisper of yours is a breeze of serenity.",
    "Your embrace is a harbor where my heart anchors.",
    "With you, even the smallest moments are infinite.",
    "You are the heartbeat that syncs with mine perfectly.",
    "Your love is the fire that warms my quiet nights.",
    "Every step with you is a dance through starlight.",
    "You are the poetry I had forgotten I knew.",
    "With you, the universe feels tender and near.",
    "Your smile is the dawn that wakes my soul gently.",
    "Every touch of yours leaves a gentle spark.",
    "You are the melody I hum when the world is still.",
    "With you, life is an endless sonnet of love.",
    "Your presence turns ordinary spaces into sanctuaries.",
    "Every thought of you is a soft sigh of wonder.",
    "You are the quiet music in my loudest moments.",
    "With you, love feels like sunlight kissing the morning dew.",
    "Your gaze is the anchor that steadies my drifting heart.",
    "Every heartbeat is brighter because you are near.",
    "You are the gentle rhythm that makes my soul dance."
];


const para = document.getElementById("quote");

function generateNumber(){
    return Math.floor(Math.random() * quotes.length);
}
let prevNum = generateNumber();

function generateQuote(){
    
    let quoteNumber = generateNumber();

    if (quoteNumber === prevNum) {
        quoteNumber = (quoteNumber + 1) % quotes.length;
    }
    
    para.textContent = quotes[quoteNumber];
    prevNum = quoteNumber
}